SELECT NAME FROM
(SELECT SUM(DEAL.AMOUNT) as RES, SALESMAN.NAME FROM SALESMAN
INNER JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
INNER JOIN DEAL ON DEAL.CUSTOMER_ID = CUTOMER.CUSTOMER_ID
WHERE to_char(DEAL_DATE, 'MM') = 12 AND to_char(DEAL_DATE, 'YYYY') = 2018
GROUP BY SALESMAN.NAME)
WHERE RES = (SELECT MAX(res) FROM (SELECT SUM(DEAL.AMOUNT) as RES, SALESMAN.NAME FROM SALESMAN
INNER JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
INNER JOIN DEAL ON DEAL.CUSTOMER_ID = CUTOMER.CUSTOMER_ID
WHERE to_char(DEAL_DATE, 'MM') = 12 AND to_char(DEAL_DATE, 'YYYY') = 2018
GROUP BY SALESMAN.NAME));

CREATE TABLE TEST_SPEED (
    ID NUMBER PRIMARY KEY,
    SOME_STRING NVARCHAR2(50) NOT NULL,
    SOME_NUMBER NUMBER NOT NULL
);

DROP TABLE TEST_SPEED;

CREATE TABLE ROOMS(
    ROOM_ID NUMBER PRIMARY KEY,
    NUMBEROFGUESTS NUMBER NOT NULL,
    PRICE NUMBER NOT NULL,
    BREAKFASTINCLUDED NUMBER NOT NULL,
    CONSTRAINT CHECK_BREAKFASTINCLUDED CHECK (BREAKFASTINCLUDED BETWEEN 0 AND 1),
    PETSALLOWED NUMBER NOT NULL,
    CONSTRAINT CHECK_PETSALLOWED CHECK (PETSALLOWED BETWEEN 0 AND 1),
    DATEAVAILABLEFROM TIMESTAMP NOT NULL,
    HOTEL_ID NUMBER,
    CONSTRAINT HOTEL_FK FOREIGN KEY (HOTEL_ID) REFERENCES HOTELS(HOTEL_ID)
);

CREATE TABLE HOTELS(
    HOTEL_ID NUMBER PRIMARY KEY,
    NAMEOFHOTEL NVARCHAR2(50) NOT NULL,
    COUNTRY NVARCHAR2(50) NOT NULL,
    CITY NVARCHAR2(50) NOT NULL,
    STREET NVARCHAR2(50) NOT NULL
);