CREATE TABLE ROOMS(
    ROOM_ID NUMBER PRIMARY KEY,
    NUMBEROFGUESTS NUMBER NOT NULL,
    PRICE NUMBER NOT NULL,
    BREAKFASTINCLUDED NUMBER NOT NULL,
    CONSTRAINT CHECK_BREAKFASTINCLUDED CHECK (BREAKFASTINCLUDED BETWEEN 0 AND 1),
    PETSALLOWED NUMBER NOT NULL,
    CONSTRAINT CHECK_PETSALLOWED CHECK (PETSALLOWED BETWEEN 0 AND 1),
    DATEAVAILABLEFROM TIMESTAMP NOT NULL,
    HOTEL_ID NUMBER,
    CONSTRAINT HOTEL_FK FOREIGN KEY (HOTEL_ID) REFERENCES HOTELS(HOTEL_ID)
);

CREATE TABLE HOTELS(
    HOTEL_ID NUMBER PRIMARY KEY,
    NAMEOFHOTEL NVARCHAR2(50) NOT NULL,
    COUNTRY NVARCHAR2(50) NOT NULL,
    CITY NVARCHAR2(50) NOT NULL,
    STREET NVARCHAR2(50) NOT NULL
);